services:
  repuMonta:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment: 
      -N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data: